### ISSUE TITLE
解像度設定の選択肢が少ない

### ISSUE THREAD

**Issue by index-0427** [m4saka/kshootmania-v2#28]
SETTINGS -> DISPLAY/SOUND SETTINGS -> SCREEN RESOLUTION (WINDOW)
最大解像度が1280x1024までしかない
![image](https://github.com/kshootmania/ksm-v2/assets/56032998/b87614df-1c29-49bf-9c55-40d64ba9b478)

**Comment by m4saka** [comment]
かつ、解像度設定が反映されない(未実装のため)

**Comment by m4saka** [comment]
v1(HSP版)でも同様だったので仕様のようでした。
ただ、1280x1024より大きい解像度も選べるべきなので改善します。
![image](https://github.com/kshootmania/ksm-v2/assets/14288724/7d79a5eb-15c7-4ec0-aabe-632babacee7c)

**Comment by m4saka** [comment]
追加完了
